# Generated by Django 4.0.4 on 2022-10-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paczkomat',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc', models.CharField(max_length=3)),
                ('error_list', multiselectfield.db.fields.MultiSelectField(choices=[('brak_ceownika', 'Brak ceownika'), ('brak_elementów_zlacznych', 'Brak elementów złącznych'), ('brak_markera', 'Brak markera'), ('brak_nagran_z_kamer', 'Brak nagrań z kamer'), ('brak_naklejek_zs', 'Brak naklejek ZS'), ('brak_nitow', 'Brak nitów'), ('brak_obrazu', 'Brak obrazu'), ('brak_odbojnikow', 'Brak odbojników'), ('brak_pieczatki_qc', 'Brak pieczątki QC'), ('brak_przepustu_kablowego', 'Brak przepustu kablowego'), ('brak_segerów', 'Brak segerow'), ('brak_uchwytu_przewodow', 'Brak uchwytu przewodów'), ('brak_uszczelki', 'Brak uszczelki'), ('brak_zaslepki_dachowej', 'Brak zaślepki dachowej'), ('brak_zlacza_qpd', 'Brak złącza QPD'), ('drzwiczki_do_regulacji', 'Drzwiczki do regulacji'), ('niedokrecona_krancowka', 'Niedokręcona krańcówka'), ('niedokrecona_nakretka_drzwiczek', 'Niedokręcona nakrętka drzwiczek'), ('niedokrecona_sruba', 'Niedokręcona śruba'), ('niedokrecony_przewod', 'Niedokręcony przewód'), ('niedokrecone_uziemienie', 'Niedokręcone uziemienie'), ('niedokrecony_zawias_drzwiczek', 'Niedokręcony zawias drzwiczek'), ('niedzialajaca_kamera', 'Niedziałająca kamera'), ('niedzialajac_dvr', 'Niedziałający DVR'), ('niepoprawne_podlaczenie_przewodow', 'Niepoprawne podłączenie przewodów'), ('niezabezpieczony_przewod', 'Niezabezpieczony przewód'), ('opilki_w_skrytkach', 'Opiłki w skrytkach'), ('pozostawione_el_zlaczne', 'Pozostawione elementy złączne'), ('uszkodzenia_pow_lakierniczej', 'Uszkodzenia powierzchni lakierniczej'), ('uszkodzona_polka', 'Uszkodzona półka'), ('uszkodzone_drzwiczki', 'Uszkodzone drzwiczki'), ('uszkodzony_felc', 'Uszkodzony felc'), ('uszkodzony_przewod', 'Uszkodzony przewód'), ('wadliwa_sciana_modulu', 'Wadliwa ściana modułu'), ('wystajace_nity', 'Wystające nity')], max_length=711)),
                ('other_error', models.CharField(blank=True, max_length=50, null=True)),
                ('parcel_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iop_app.parcelmachine')),
            ],
            options={
                'verbose_name_plural': 'Pracownik',
            },
        ),
    ]
