# Generated by Django 4.0.4 on 2022-10-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('parcel_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iop_app.worker')),
            ],
        ),
    ]
