# Generated by Django 4.0.4 on 2022-10-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0002_counterrors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterrors',
            name='parcel_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iop_app.parcelmachine'),
        ),
    ]
