# Generated by Django 4.1.4 on 2023-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0004_delete_counterrors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('brak_ceownika', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_elementow_zlacznych', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_markera', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_nagran_z_kamer', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_naklejek_zs', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_nitow', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_obrazu', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_odbojnikow', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_pieczatki_qc', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_przepustu_kablowego', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_segerow', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_uchwytu_przewodow', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_uszczelki', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_zaslepki_dachowej', models.IntegerField(blank=True, default=None, null=True)),
                ('brak_zlacza_gpd', models.IntegerField(blank=True, default=None, null=True)),
                ('drzwiczki_do_regulacji', models.IntegerField(blank=True, default=None, null=True)),
                ('niedokrecona_krancowka', models.IntegerField(blank=True, default=None, null=True)),
                ('niedokrecona_nakretka_drzwiczek', models.IntegerField(blank=True, default=None, null=True)),
                ('niedokrecona_sruba', models.IntegerField(blank=True, default=None, null=True)),
                ('niedokrecony_przewod', models.IntegerField(blank=True, default=None, null=True)),
                ('niedokrecone_uziemienie', models.IntegerField(blank=True, default=None, null=True)),
                ('niedokrecony_zawias_drzwiczek', models.IntegerField(blank=True, default=None, null=True)),
                ('niedzialajaca_kamera', models.IntegerField(blank=True, default=None, null=True)),
                ('niedzialajac_dvr', models.IntegerField(blank=True, default=None, null=True)),
                ('niepoprawne_podlaczenie_przewodow', models.IntegerField(blank=True, default=None, null=True)),
                ('niezabezpieczony_przewod', models.IntegerField(blank=True, default=None, null=True)),
                ('opilki_w_skrytkach', models.IntegerField(blank=True, default=None, null=True)),
                ('pozostawione_el_zlaczne', models.IntegerField(blank=True, default=None, null=True)),
                ('uszkodzenia_pow_lakierniczej', models.IntegerField(blank=True, default=None, null=True)),
                ('uszkodzona_polka', models.IntegerField(blank=True, default=None, null=True)),
                ('uszkodzone_drzwiczki', models.IntegerField(blank=True, default=None, null=True)),
                ('uszkodzony_felc', models.IntegerField(blank=True, default=None, null=True)),
                ('uszkodzony_przewod', models.IntegerField(blank=True, default=None, null=True)),
                ('wadliwa_sciana_modulu', models.IntegerField(blank=True, default=None, null=True)),
                ('wystajace_nity', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='error_list',
        ),
    ]
