# Generated by Django 4.1.4 on 2023-01-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0006_worker_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='errors',
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_ceownika',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_elementow_zlacznych',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_markera',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_nagran_z_kamer',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_naklejek_zs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_nitow',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_obrazu',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_odbojnikow',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_pieczatki_qc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_przepustu_kablowego',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_segerow',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_uchwytu_przewodow',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_uszczelki',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_zaslepki_dachowej',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='brak_zlacza_gpd',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='drzwiczki_do_regulacji',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedokrecona_krancowka',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedokrecona_nakretka_drzwiczek',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedokrecona_sruba',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedokrecone_uziemienie',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedokrecony_przewod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedokrecony_zawias_drzwiczek',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedzialajac_dvr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niedzialajaca_kamera',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niepoprawne_podlaczenie_przewodow',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='niezabezpieczony_przewod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='opilki_w_skrytkach',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='pozostawione_el_zlaczne',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='uszkodzenia_pow_lakierniczej',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='uszkodzona_polka',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='uszkodzone_drzwiczki',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='uszkodzony_felc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='uszkodzony_przewod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='wadliwa_sciana_modulu',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='wystajace_nity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='ErrorCount',
        ),
    ]
