# Generated by Django 4.0.4 on 2023-01-03 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0007_remove_worker_errors_worker_brak_ceownika_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
