# Generated by Django 4.0.4 on 2023-01-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0008_worker_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
