# Generated by Django 4.0.4 on 2023-02-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0010_remove_worker_other_error_alter_worker_brak_ceownika_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelmachine',
            name='description',
            field=models.TextField(blank=True, default='Brak', null=True),
        ),
    ]
