# Generated by Django 4.0.4 on 2023-02-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0011_alter_parcelmachine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmachine',
            name='sum_of_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
