# Generated by Django 4.0.4 on 2023-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0012_parcelmachine_sum_of_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelmachine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
