# Generated by Django 4.0.4 on 2023-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0013_alter_parcelmachine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='brak_elementow_zlacznych',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Elementów Złącznych'),
        ),
    ]
