# Generated by Django 4.0.4 on 2023-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0014_alter_worker_brak_elementow_zlacznych'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='brak_ceownika',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Ceownika'),
        ),
    ]
