# Generated by Django 4.0.4 on 2023-03-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0015_alter_worker_brak_ceownika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='brak_markera',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Markera'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_nagran_z_kamer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Nagrań Z Kamer'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_naklejek_zs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Nakelejek ZS'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_nitow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Nitów'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_obrazu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Obrazu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_odbojnikow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Odbojników'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_pieczatki_qc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Pieczątki QC'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_przepustu_kablowego',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Przepustu Kablowego'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_segerow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Segerów'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_uchwytu_przewodow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Uchwytu Przewodów'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_uszczelki',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Uszczelki'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_zaslepki_dachowej',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Zaślepki Dachowej'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='brak_zlacza_gpd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brak Złącza GPD'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='drzwiczki_do_regulacji',
            field=models.IntegerField(blank=True, null=True, verbose_name='Drzwiczki Do Regulacji'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedokrecona_krancowka',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedokręcona Krańcówka'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedokrecona_nakretka_drzwiczek',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedokręcona Nakrętka Drzwiczek'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedokrecona_sruba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedokręcona Śruba'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedokrecone_uziemienie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedokręcone Uziemienie'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedokrecony_przewod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedokręcony Przewód'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedokrecony_zawias_drzwiczek',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedokręcony Zawias Drzwiczek'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedzialajac_dvr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedziałający DVR'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niedzialajaca_kamera',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niedziałająca Kamer'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niepoprawne_podlaczenie_przewodow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niepoprawne Podłączenie Przewodów'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='niezabezpieczony_przewod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niezabezpieczony Przewód'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='opilki_w_skrytkach',
            field=models.IntegerField(blank=True, null=True, verbose_name='Opiłki W Skrytkach'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pozostawione_el_zlaczne',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pozowstawione Elementy Złączne'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='uszkodzenia_pow_lakierniczej',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uszkodzenia Powłoki Lakierniczej'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='uszkodzona_polka',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uszkodzona Półka'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='uszkodzone_drzwiczki',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uszkodzone Drzwiczki'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='uszkodzony_felc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uszkodzony Felc'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='uszkodzony_przewod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uszkodzony Przewód'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wadliwa_sciana_modulu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wadliwa Ściana Modułu'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wystajace_nity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wystające Nity'),
        ),
    ]
