# Generated by Django 4.0.4 on 2023-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop_app', '0016_alter_worker_brak_markera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='qc',
            field=models.CharField(max_length=3, verbose_name='QC'),
        ),
    ]
